[DRAFT] - Authentication (and Authorization)
datatorch/datatorch pull request #198
Opened 2021-06-10 04:23 UTC by Zanibas

Implements:

- Refresh and access tokens
- Stores those tokens in cookies and also provides them in the mutation response.
- Login and register pages now work at an MVP level, without redirecting

TODO:
- Cookies need to actually save when not accessing via port 4000, instead from port 3000
- Authorization checks for protected pages
- Need to test if the viewer query works
- Method for invalidating tokens
- Probably some more stuff?

2021-06-15 15:14 UTC, jsbroks requested changes

2021-06-15 15:14 UTC, jsbroks commented on clients/web/src/graphql/queries/ProjectOwner.gql
> +}
Each query/mutation should be in there own file. and mutations should be in the mutations dir

2021-06-15 15:14 UTC, jsbroks commented on clients/web/src/pages/login.tsx
> +  }
Remove console log and  `${result.data.login.userId}` username would probably be better

2021-06-15 15:14 UTC, jsbroks commented on clients/web/src/pages/register.tsx
> +  }
remove `eslint-disable-next-line no-console` + using username

2021-06-15 15:14 UTC, jsbroks commented on services/api/src/context.ts
> +export const TOKEN_SECRET = 'REPLACETHISWITHSOMETHINGELSE'
use `process.env.TOKEN_SECRET ?? 'default'`

2021-06-15 15:14 UTC, jsbroks commented on services/api/src/modules/ProjectOwner.ts
> +    t.field(PO.role.name, PO.role)
I would use full name `ProjectOwner` to be explict

2021-06-15 15:14 UTC, jsbroks commented on services/api/src/modules/ProjectOwner.ts
> +})
Full name for Project

2021-06-15 15:14 UTC, jsbroks commented on services/api/src/modules/ProjectOwner.ts
> +})
I think the auth payload should have a user resolver, which can return the user Id

2021-06-15 15:14 UTC, jsbroks commented on services/api/src/tokens.ts
> +export enum LoginOrRegister {
Maybe `AuthAction` would be a bettername

2021-06-15 15:14 UTC, jsbroks commented on services/api/src/tokens.ts
> +// hook function to run before accessing pages that require auth.
Use JSDocs format

2021-06-15 15:14 UTC, jsbroks commented on shared/prisma/schema.vuerd.json
> +{
What is this file?

2021-06-15 15:14 UTC, jsbroks commented
You can set the PR to WIP

2021-06-15 15:17 UTC, jsbroks commented on services/api/src/tokens.ts
> +// hook function to run before accessing pages that require auth.
Is there not a `FastifyHookFunction` type? Or something like it?

2021-06-15 15:18 UTC, jsbroks commented on services/api/src/tokens.ts
> +    const unsignedAccessToken = request.unsignCookie(signedAccessToken)
`const {valid, value} = request.unsignCookie(signedAccessToken)`

2021-06-15 15:20 UTC, jsbroks commented on services/api/src/tokens.ts
> +    return
not needed

2021-06-16 07:20 UTC, Zanibas commented on clients/web/src/pages/login.tsx
> +  }
This is just a placeholder for now to confirm success, will redirect to home page of user after login.

2021-11-17 03:55 UTC, merged